### PR TITLE
Add canonize tests

### PR DESCRIPTION
**Pull request by aljones15**
Adds basics test for canonization and hashing values.
This should allow me to better confirm that the canonization is remaining consistent when upgrading jsigs.

### CODE REVIEW

**Comment by gannan08** [comment]
@aljones15 Can you speak to how this differs from https://github.com/digitalbazaar/bedrock-ledger-node/pull/106?

**Comment by davidlehn** [comment]
> @aljones15 Can you speak to how this differs from #106?

Based on different branch to test different jsonld versions.

**Review by davidlehn — APPROVED** [review]
Not sure if it's better to rename 10- test to 11- like this or just have the new one be 05-.  Would like some other reviewers to decided if this gives enough confidence for jsonld/canonize updates.

**Comment by aljones15** [comment]
> Not sure if it's better to rename 10- test to 11- like this or just have the new one be 05-. Would like some other reviewers to decided if this gives enough confidence for jsonld/canonize updates.

awaiting this decision before rebasing into master.

**Comment by gannan08** [comment]
I'd have the new one be named `05-`. This provides a good start to raising confidence for jsonld/canonize updates.

**Pull request merged**
